version: "3"
services:
  kanboard:
    build:
      context: .
    image: kanboard/kanboard:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./kanboard_data:/var/www/app/data
      - ./kanboard_plugins:/var/www/app/plugins
      - ./kanboard_ssl:/etc/nginx/ssl
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    restart: unless-stopped

volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl:
