version: "3"
services:
  kanboard:
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./kanboard_data:/var/www/app/data:z
      - ./kanboard_plugins:/var/www/app/plugins:z
      - ./kanboard_ssl:/etc/nginx/ssl:z
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    restart: unless-stopped

volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl:
